apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app
  labels:
    app: my-app
    version: canary
spec:
  replicas: 2  # Canary version starts with fewer replicas
  selector:
    matchLabels:
      app: my-app
      version: canary
  template:
    metadata:
      labels:
        app: my-app
        version: canary
    spec:
      containers:
        - name: my-app-container
          image: tomcat  # Replace with the canary version image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: canary-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
    version: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
